development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  pool: 5
  username: wynnemlo
  password: candy123

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  username: wynnemlo
  password: candy123
