development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  pool: 5
  username: Kevin
  password: 98bnsrgk

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  username: Kevin
  password: 98bnsrgk
